<?php

$config = new PhpCsFixer\Config();
return $config
	->setRiskyAllowed(true)
	->setRules([
		'array_indentation' => true,
		'array_syntax' => ['syntax' => 'short'],
		'binary_operator_spaces' => true,
		'blank_line_after_namespace' => true,
		'blank_line_after_opening_tag' => true,
		'blank_line_before_statement' => ['statements'=>['return']],
		'braces' => ['allow_single_line_closure' => false],
		'cast_spaces' => true,
//		'class_attributes_separation' => ['const' => 'one','method' => 'one','property' => 'one','trait_import' => 'none'],
		'class_definition' => ['single_line'=>true],
		'combine_consecutive_issets' => true,
		'concat_space' => ['spacing' => 'one'],
		'declare_equal_normalize' => true,
		'elseif' => true,
		'encoding' => true,
		'full_opening_tag' => true,
		'function_declaration' => true,
		'function_typehint_space' => true,
		'include' => true,
		'increment_style' => true,
		'indentation_type' => true,
		'line_ending' => true,
		'linebreak_after_opening_tag' => true,
		'lowercase_cast' => true,
		'lowercase_keywords' => true,
		'lowercase_static_reference' => true,
		'magic_constant_casing' => true,
		'magic_method_casing' => true,
		'mb_str_functions' => false,
		'method_argument_space' => true,
		'native_function_casing' => true,
		'native_function_invocation' => ['include'=>['@all']],
		'native_function_type_declaration_casing' => true,
		'new_with_braces' => true,
		'no_blank_lines_after_class_opening' => true,
		'no_blank_lines_after_phpdoc' => true,
		'no_break_comment' => true,
		'no_closing_tag' => true,
		'no_empty_comment' => true,
		'no_empty_phpdoc' => true,
		'no_empty_statement' => true,
		'no_extra_blank_lines' =>
			['tokens'=>
				[
				'curly_brace_block',
				'extra',
				'parenthesis_brace_block',
				'square_brace_block',
				'throw',
				'use',
				]
			],
		'no_leading_import_slash' => true,
		'no_leading_namespace_whitespace' => true,
		'no_mixed_echo_print' => true,
		'no_multiline_whitespace_around_double_arrow' => true,
		'no_null_property_initialization' => true,
		'no_short_bool_cast' => true,
		'no_singleline_whitespace_before_semicolons' => true,
		'no_superfluous_elseif' => true,
		'no_spaces_after_function_name' => true,
		'no_spaces_around_offset' => true,
		'no_spaces_inside_parenthesis' => true,
		'no_superfluous_phpdoc_tags' => ['allow_mixed' => true, 'allow_unused_params' => true],
		'no_trailing_comma_in_list_call' => true,
		'no_trailing_comma_in_singleline_array' => true,
		'no_trailing_whitespace' => true,
		'no_trailing_whitespace_in_comment' => true,
		'no_unneeded_control_parentheses' => true,
		'no_unneeded_curly_braces' => ['namespaces' => true],
		'no_unused_imports' => true,
		'no_useless_else' => true,
		'no_useless_return' => true,
		'no_whitespace_before_comma_in_array' => true,
		'no_whitespace_in_blank_line' => true,
		'normalize_index_brace' => true,
		'not_operator_with_space' => false,
		'object_operator_without_whitespace' => true,
		'ordered_class_elements' => true,
		'ordered_imports' => true,
		'php_unit_fqcn_annotation' => true,
		'phpdoc_align' =>
			['tags' =>
				[
				'method',
				'param',
				'property',
				'property-read',
				'return',
				'throws',
				'type',
				'var',
				]
			],
		'phpdoc_add_missing_param_annotation' => true,
		'phpdoc_annotation_without_dot' => true,
		'phpdoc_indent' => true,
		'phpdoc_inline_tag_normalizer' => true,
		'phpdoc_no_access' => true,
		'phpdoc_no_alias_tag' => false,
		'phpdoc_no_package' => true,
		'phpdoc_no_useless_inheritdoc' => true,
		'phpdoc_order' => true,
		'phpdoc_return_self_reference' => true,
		'phpdoc_scalar' => true,
		'phpdoc_separation' => true,
		'phpdoc_single_line_var_spacing' => true,
		'phpdoc_summary' => true,
		'phpdoc_to_comment' => true,
		'phpdoc_trim' => true,
		'phpdoc_trim_consecutive_blank_line_separation' => true,
		'phpdoc_types' => true,
		'phpdoc_types_order' => ['null_adjustment' => 'always_last', 'sort_algorithm' => 'none'],
		'phpdoc_var_without_name' => true,
		'return_assignment' => true,
		'return_type_declaration' => true,
		'semicolon_after_instruction' => true,
		'simplified_null_return' => true,
		'short_scalar_cast' => true,
		'single_blank_line_at_eof' => true,
		'single_blank_line_before_namespace' => true,
		'single_class_element_per_statement' => true,
		'single_import_per_statement' => true,
		'single_line_after_imports' => true,
		'single_line_comment_style' => ['comment_types' => ['hash']],
		'single_line_throw' => true,
		'single_quote' => true,
		'single_trait_insert_per_statement' => true,
		'space_after_semicolon' => ['remove_in_empty_for_expressions'=>true],
		'standardize_increment' => true,
		'standardize_not_equals' => true,
		'switch_case_semicolon_to_colon' => true,
		'switch_case_space' => true,
		'ternary_operator_spaces' => true,
		'ternary_to_null_coalescing' => true,
		'trailing_comma_in_multiline' => true,
		'trim_array_spaces' => true,
		'unary_operator_spaces' => true,
		'visibility_required' => true,
		'whitespace_after_comma_in_array' => true,
		'yoda_style' => false,
	])
	->setFinder(PhpCsFixer\Finder::create()
		->exclude('vendor')
		->in('src')
		->in('tests')
	)
;
